#!/usr/bin/env python

from __future__ import print_function

from contextlib import contextmanager
from copy import deepcopy
from distutils.spawn import find_executable
from glob import glob
from itertools import chain
import os
from subprocess import call, check_output
import sys
from tempfile import NamedTemporaryFile
from time import sleep

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PROFILES_DIR = os.path.join(BASE_DIR, 'profiles')
GLOB_PROFILE_MAP = {
    'bower.json': 'frontend',
    'package.json': 'frontend',
    'app/assets': 'frontend', # Rails
    'manage.py': 'python', # Django
    'README.rst': 'python',
    'requirements.txt': 'python',
    'setup.py': 'python',
    '*.gemspec': 'ruby',
    'Gemfile': 'ruby',
    'Cargo.toml': 'rust',
}


def vim_impl(vim):
    if vim == 'nvim':
        return 'nvim'
    else:
        return 'vim'


def home_vimdir(vim):
    vim_folder = vim_impl(vim)
    cfg = os.environ.get('XDG_CONFIG_HOME', os.path.expanduser('~/.config'))
    vimdir = os.path.join(cfg, vim_folder)
    if not os.path.exists(vimdir):
        os.makedirs(vimdir)
    return vimdir


def profile_dirs(profiles):
    for profile in profiles:
        yield os.path.join(PROFILES_DIR, profile)


def generate_runtimepath(vim,profiles):
    common_vimdirs = [
        '$VIM/vimfiles',
        '$VIMRUNTIME',
        BASE_DIR,  # for vimrc.d
        '$VIM/vimfiles/after',
    ]
    profile_vimdirs = [vdir for vdir in profile_dirs(profiles) if os.path.isdir(vdir)]
    vimdirs = profile_vimdirs + common_vimdirs
    return 'set runtimepath={}'.format(','.join(vimdirs))


def pathogen_cmds(vim, profiles):
    bundle_dirs = ["'{}/bundle/{{}}'".format(p) for p in profile_dirs(profiles)]
    return '''
if has("mac")
  set nocp
endif
runtime vim/bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect({bundle_dirs})
set runtimepath^={home_vimdir}
Helptags
'''.format(home_vimdir=home_vimdir(vim),
           bundle_dirs=','.join(bundle_dirs)).strip()


def impl_profiles(vim, profiles):
    impl = vim_impl(vim)
    for profile in chain(['common'], profiles):
        yield [profile, '{}-{}'.format(profile, impl)]


def generate_vimrc(vim, profiles):
    all_profiles = list(chain.from_iterable(impl_profiles(vim, profiles)))
    vimrc_d_glob = os.path.join(BASE_DIR, 'vimrc.d', '*.vim')
    vimrc_d_files = [f.replace(os.path.join(BASE_DIR, ''), '')
                     for f in glob(vimrc_d_glob) if '001-pathogen' not in f]
    runtime_vimrc_d = '\n'.join(['runtime {}'.format(f)
                                 for f in sorted(vimrc_d_files)])
    vimrc = u'''
runtime vimrc
{runtimepath}
{pathogen}
{vimrc_d}
'''.format(runtimepath=generate_runtimepath(vim, all_profiles),
           pathogen=pathogen_cmds(vim, all_profiles),
           vimrc_d=runtime_vimrc_d)
    return vimrc.encode('utf-8')


def run_cmd(cmd):
    return str(check_output(cmd, shell=True).strip())


def get_rust_src():
    sysroot = run_cmd('rustc --print sysroot')
    return os.path.join(sysroot, 'lib', 'rustlib', 'src', 'rust', 'src')

def set_rvm_libdir(environ):
    rvm_libdir = run_cmd('rvm config-get libdir')
    if 'LD_LIBRARY_PATH' in environ:
        environ['LD_LIBRARY_PATH'] += os.pathsep + rvm_libdir
    else:
        environ['LD_LIBRARY_PATH'] = rvm_libdir


def set_rust_src_path(environ):
    default_rust_src_path = get_rust_src()
    if os.path.isdir(default_rust_src_path):
        environ['RUST_SRC_PATH'] = default_rust_src_path


def set_nvim_environment(environ):
    environ['EDITOR'] = 'nvim'
    # Needed for truecolor support
    if 'TMUX' in environ:
        ncurses_version = run_cmd('reset -V').split(' ', 2)[1]
        if int(ncurses_version.split('.')[0]) < 6:
            environ['TERM'] = 'screen-256color'
        else:
            environ['TERM'] = 'tmux-256color'
    else:
        environ['TERM'] = 'xterm-256color'
    # Needed for Neovim < 0.1.5
    environ['NVIM_TUI_ENABLE_TRUE_COLOR'] = '1'
    # cursor shapes don't work with Debian Jessie's vte
    if not (find_executable('lsb_release') and
            run_cmd('lsb_release --codename --short').strip() == 'jessie'):
        environ['NVIM_TUI_ENABLE_CURSOR_SHAPE'] = '1'


@contextmanager
def generated_vimrc(vim, profiles):
    with NamedTemporaryFile() as vimrc:
        vimrc.write(generate_vimrc(vim, profiles))
        vimrc.flush()
        yield vimrc


def call_vim(vim, vimrc, vim_args, environ):
    cmd = [vim, '-u', vimrc.name] + vim_args
    if 'VIM_GDB' in environ:
        cmd = ['gdb', '--args'] + cmd
    return call(cmd, env=environ)


def run_vim(prog_name, profiles, vim_args):
    vim = prog_name[:prog_name.index('-')]
    environ = deepcopy(os.environ)
    if find_executable('rvm'):
        set_rvm_libdir(environ)
    if 'rust' in profiles and 'RUST_SRC_PATH' not in environ:
        set_rust_src_path(environ)
    if vim == 'nvim':
        set_nvim_environment(environ)
    with generated_vimrc(vim, profiles) as vimrc:
        retcode = call_vim(vim, vimrc, vim_args, environ)
        if vim.startswith('mvim'):
            # MacVim loads too slowly, the generated vimrc file is deleted
            # before it tries to load it.
            sleep(5)
        return retcode


def detect_profiles():
    return [profile for suffix, profile in GLOB_PROFILE_MAP.items()
                    if glob(os.path.join(os.path.curdir, suffix))]


def list_profiles():
    print('List of profiles (common and common-{vim,nvim} are default):')
    for d in os.listdir(PROFILES_DIR):
        if os.path.isdir(os.path.join(PROFILES_DIR, d)) and not d.endswith(('-vim', '-nvim')):
            print('* {}'.format(d))
    return 0


def list_profileless_bundles():
    bundle_dir = os.path.join(BASE_DIR, 'vim', 'bundle')
    all_bundles = [d for d in os.listdir(bundle_dir)
                   if os.path.isdir(os.path.join(bundle_dir, d))]
    profile_glob = os.path.join(PROFILES_DIR, '*', 'bundle', '*')
    bundles_in_profiles = [os.path.basename(l) for l in glob(profile_glob)
                           if os.path.islink(l)]
    profileless_bundles = sorted(set(all_bundles) - set(bundles_in_profiles))
    if len(profileless_bundles) > 0:
        print('List of bundles not in any profile:')
        [print('* {}'.format(b)) for b in profileless_bundles]
    else:
        print('All bundles are in at least one profile.')
    return 0


def main(args):
    prog_name = args[0]
    if len(args) < 1:
        usage_msg = '''\
Usage: {} (PROFILE_NAMES | --list-profiles | --list-profileless-bundles) \
[Vim args...]

Where PROFILE_NAMES is a comma-separated list of profiles to use.
The "common" profile is enabled by default.
'''.format(prog_name)
        print(usage_msg, file=sys.stderr)
        return 1
    prog_name = os.path.basename(prog_name)
    if len(args) > 1:
        profiles = args[1].split(',')
    else:
        profiles = detect_profiles()
    if profiles == ['--list-profiles']:
        return list_profiles()
    elif profiles == ['--list-profileless-bundles']:
        return list_profileless_bundles()
    else:
        return run_vim(prog_name, profiles, args[2:])

if __name__ == '__main__':
    sys.exit(main(sys.argv))
